### PR TITLE
Using standard trim function

### PR DESCRIPTION
**Pull request by evertonfraga**
Fixes https://github.com/ethereum/mist/issues/446.

### CODE REVIEW

**Comment by luclu** [comment]
Uhh, that's awesome!!

**Comment by evertonfraga** [comment]
mistyped: even less error-prone :)

**Comment by luclu** [comment]
BTW, just arrived back in China - no problems.. ;)

**Comment by evertonfraga** [comment]
@luclu surprisingly I don't have access to that original repo, could you merge that for me plz?

re China: awesome :)

**Comment by luclu** [comment]
me, neither ;) pinging @frozeman

**Pull request merged**
